### ISSUE TITLE
NodeJS 400 Error

### ISSUE THREAD

**Issue by joshlsullivan** [sendgrid/docs#5904]
Hi there, I'm trying to send from ExpressJS and receive the following error:

```
ResponseError: Bad Request
    at Request._callback (node_modules/@sendgrid/client/src/classes/client.js:124:25)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at Request.emit (events.js:316:20)
    at Request.<anonymous> (node_modules/request/request.js:1154:10)
    at Request.emit (events.js:316:20)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:422:28)
    at IncomingMessage.emit (events.js:328:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 400,
  message: 'Bad Request',
  response: {
    headers: {
      server: 'nginx',
      date: 'Mon, 30 Mar 2020 02:56:08 GMT',
      'content-type': 'application/json',
      'content-length': '402',
      connection: 'close',
      'access-control-allow-origin': 'https://sendgrid.api-docs.io',
      'access-control-allow-methods': 'POST',
      'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
      'access-control-max-age': '600',
      'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html'
    },
    body: { errors: [Array] }
  }
}
```

**Comment by astuteape** [comment]
Hello @joshlsullivan  ,
We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.
Twilio SendGrid Docs Team
